package com.studyloop.backend.video;

import com.studyloop.backend.config.VideoProperties;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

// Where finished videos live, and the only place this application writes them.
//
// Deliberately the same shape as DocumentStorageService: an absolute root from configuration, a
// relative path stored on the entity, and a resolve() the reader goes through. The reason is
// Phase 23.4 rather than tidiness — a deploy has to decide on one volume for user-generated bytes,
// and two services with two conventions would make that two decisions and one of them would be
// forgotten.
//
// **The worker does not write here.** It renders into its own scratch directory and hands the
// finished bytes back over HTTP; this service writes them. In development the two processes do
// not even share a filesystem — the backend runs on Windows and the renderer inside a Linux
// container — so a shared volume would have been a path that resolves in one deployment and not
// in the other.
@Service
public class VideoStorageService {

    private final Path root;

    public VideoStorageService(VideoProperties properties) {
        this.root = Path.of(properties.videosDir()).toAbsolutePath().normalize();
    }

    // "{courseId}/{jobId}.mp4". Job-addressed rather than content-addressed, unlike documents:
    // two videos of the same topic are not the same file, and there is nothing to deduplicate.
    public String storeVideo(UUID courseId, UUID jobId, byte[] bytes) {
        return write(courseId + "/" + jobId + ".mp4", bytes);
    }

    public String storeCaptions(UUID courseId, UUID jobId, String vtt) {
        return write(courseId + "/" + jobId + ".vtt", vtt.getBytes(StandardCharsets.UTF_8));
    }

    // The generated Manim module for one scene, kept whether it rendered or not. Two kilobytes of
    // text that turn "scene 3 fell back" into a reproducible bug report.
    public String storeSceneCode(UUID courseId, UUID jobId, int sceneIndex, String code) {
        return write(courseId + "/" + jobId + "/scene-" + sceneIndex + ".py",
                code.getBytes(StandardCharsets.UTF_8));
    }

    public Path resolve(String relativePath) {
        return root.resolve(relativePath);
    }

    public byte[] read(String relativePath) {
        try {
            return Files.readAllBytes(root.resolve(relativePath));
        } catch (IOException e) {
            throw new VideoWorkerException("Could not read the stored video.", e);
        }
    }

    public boolean exists(String relativePath) {
        return relativePath != null && Files.exists(root.resolve(relativePath));
    }

    // Everything a job wrote, removed together. Called when a job is deleted; not called on
    // failure, because a failed job keeps its scene code for exactly the reason above.
    public void deleteJob(UUID courseId, UUID jobId) {
        deleteQuietly(root.resolve(courseId + "/" + jobId + ".mp4"));
        deleteQuietly(root.resolve(courseId + "/" + jobId + ".vtt"));
        Path codeDir = root.resolve(courseId + "/" + jobId);
        if (!Files.isDirectory(codeDir)) {
            return;
        }
        try (var entries = Files.list(codeDir)) {
            entries.forEach(VideoStorageService::deleteQuietly);
        } catch (IOException e) {
            return;
        }
        deleteQuietly(codeDir);
    }

    private String write(String relativePath, byte[] bytes) {
        Path target = root.resolve(relativePath);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, bytes);
        } catch (IOException e) {
            throw new VideoWorkerException("Could not store the rendered video.", e);
        }
        return relativePath;
    }

    private static void deleteQuietly(Path path) {
        try {
            Files.deleteIfExists(path);
        } catch (IOException e) {
            // A leftover file is a disk-space problem, not a correctness one, and the caller is
            // usually in the middle of answering a request.
        }
    }
}
