package com.studyloop.backend.document;

// Why a page was routed to the vision model (Phase 15.1). One value per failure *mechanism*, not
// per symptom, because the mechanism is what a reader of the fixture report needs in order to
// argue with the threshold that produced it.
//
// A page with no defect is not represented here — PageQuality holds a null instead. An `OK`
// constant would read as a fifth kind of finding, and the whole point of the router is that most
// pages are findings-free.
public enum PageDefect {

    // Almost no extractable text and an image covering the page. The page is a photograph of
    // writing: the characters were never in the file, so there is nothing for PDFBox to be good or
    // bad at. This is the case ordinary OCR also handles, and the only one of the four it does.
    SCANNED,

    // Text came out, and it is not text. A PDF maps byte codes to glyphs, and the /ToUnicode CMap
    // is the optional table saying which character each glyph *means*; when it is missing, wrong,
    // or generated by a tool that gave up, extraction returns codepoints from the private use area
    // or from an unrelated script. This is the mechanism behind pasting from a PDF and getting
    // gibberish — the file renders perfectly, because rendering never consults that table.
    BROKEN_ENCODING,

    // The characters are right and their order is not. PDFBox reads glyphs in the order the content
    // stream draws them, which on a two-column page runs down the left column and then the right —
    // or interleaves them, if the typesetter emitted them line by line across the gutter. Sorting
    // by position fixes the common case and not this one, which is the objection that rules out
    // plain OCR as the fallback: Tesseract has the same failure on the same pages.
    UNRELIABLE_ORDER,

    // Extraction worked; it just did not read the picture. A page whose substance is a plot, a
    // tree diagram or a table rendered as an image extracts its caption and its axis labels and
    // loses the thing they refer to. Phase 12 and 13 both measured figure questions as the weakest
    // kind in the golden set, and Phase 14 demonstrated that no amount of generated *text* touches
    // them.
    FIGURE
}
